# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"\x1d\n\x0bReadFileRsp\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"2\n\x0bReadFileReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\"C\n\x0cWriteFileReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x03 \x01(\x0c\"\n\n\x08WriteRsp\"\x1f\n\x0b\x46ileOpenReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"8\n\rFileCreateReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rchunks_number\x18\x02 \x01(\x03\"7\n\x0c\x44\x61tanodeList\x12\x14\n\x0clocalization\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x1e\n\x0c\x44\x61tanodeInfo\x12\x0e\n\x06socket\x18\x01 \x01(\t\"C\n\x0b\x43hunkReport\x12\x10\n\x08partname\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t2Q\n\x04\x46ile\x12$\n\x04read\x12\x0c.ReadFileReq\x1a\x0c.ReadFileRsp\"\x00\x12#\n\x05write\x12\r.WriteFileReq\x1a\t.WriteRsp\"\x00\x32\xaa\x01\n\x0fNameNodeService\x12\'\n\x04open\x12\x0c.FileOpenReq\x1a\r.DatanodeList\"\x00\x30\x01\x12+\n\x06\x63reate\x12\x0e.FileCreateReq\x1a\r.DatanodeList\"\x00\x30\x01\x12\x1f\n\x04ping\x12\r.DatanodeInfo\x1a\x06.Empty\"\x00\x12 \n\x06report\x12\x0c.ChunkReport\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READFILERSP']._serialized_start=14
  _globals['_READFILERSP']._serialized_end=43
  _globals['_READFILEREQ']._serialized_start=45
  _globals['_READFILEREQ']._serialized_end=95
  _globals['_WRITEFILEREQ']._serialized_start=97
  _globals['_WRITEFILEREQ']._serialized_end=164
  _globals['_WRITERSP']._serialized_start=166
  _globals['_WRITERSP']._serialized_end=176
  _globals['_FILEOPENREQ']._serialized_start=178
  _globals['_FILEOPENREQ']._serialized_end=209
  _globals['_FILECREATEREQ']._serialized_start=211
  _globals['_FILECREATEREQ']._serialized_end=267
  _globals['_DATANODELIST']._serialized_start=269
  _globals['_DATANODELIST']._serialized_end=324
  _globals['_EMPTY']._serialized_start=326
  _globals['_EMPTY']._serialized_end=333
  _globals['_DATANODEINFO']._serialized_start=335
  _globals['_DATANODEINFO']._serialized_end=365
  _globals['_CHUNKREPORT']._serialized_start=367
  _globals['_CHUNKREPORT']._serialized_end=434
  _globals['_FILE']._serialized_start=436
  _globals['_FILE']._serialized_end=517
  _globals['_NAMENODESERVICE']._serialized_start=520
  _globals['_NAMENODESERVICE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
