# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"!\n\x0f\x46ileDownloadRsp\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"6\n\x0f\x46ileDownloadReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\"\t\n\x07ListReq\"\x1f\n\x0b\x46ileListReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"-\n\x0b\x46ileListRsp\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\"D\n\rFileUploadReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x03 \x01(\x0c\"\x0b\n\tUploadRsp\"\x1f\n\x0b\x46ileOpenReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"8\n\rFileCreateReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rchunks_number\x18\x02 \x01(\x03\"7\n\x0c\x44\x61tanodeList\x12\x14\n\x0clocalization\x18\x01 \x01(\t\x12\x11\n\tchunkname\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xbd\x01\n\x04\x46ile\x12\x30\n\x08\x64ownload\x12\x10.FileDownloadReq\x1a\x10.FileDownloadRsp\"\x00\x12%\n\x07listAll\x12\x08.ListReq\x1a\x0c.FileListRsp\"\x00\x30\x01\x12\x34\n\x12listChunksFromFile\x12\x0c.FileListReq\x1a\x0c.FileListRsp\"\x00\x30\x01\x12&\n\x06upload\x12\x0e.FileUploadReq\x1a\n.UploadRsp\"\x00\x32\x81\x01\n\x0fNameNodeService\x12\'\n\x04open\x12\x0c.FileOpenReq\x1a\r.DatanodeList\"\x00\x30\x01\x12+\n\x06\x63reate\x12\x0e.FileCreateReq\x1a\r.DatanodeList\"\x00\x30\x01\x12\x18\n\x04ping\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEDOWNLOADRSP']._serialized_start=14
  _globals['_FILEDOWNLOADRSP']._serialized_end=47
  _globals['_FILEDOWNLOADREQ']._serialized_start=49
  _globals['_FILEDOWNLOADREQ']._serialized_end=103
  _globals['_LISTREQ']._serialized_start=105
  _globals['_LISTREQ']._serialized_end=114
  _globals['_FILELISTREQ']._serialized_start=116
  _globals['_FILELISTREQ']._serialized_end=147
  _globals['_FILELISTRSP']._serialized_start=149
  _globals['_FILELISTRSP']._serialized_end=194
  _globals['_FILEUPLOADREQ']._serialized_start=196
  _globals['_FILEUPLOADREQ']._serialized_end=264
  _globals['_UPLOADRSP']._serialized_start=266
  _globals['_UPLOADRSP']._serialized_end=277
  _globals['_FILEOPENREQ']._serialized_start=279
  _globals['_FILEOPENREQ']._serialized_end=310
  _globals['_FILECREATEREQ']._serialized_start=312
  _globals['_FILECREATEREQ']._serialized_end=368
  _globals['_DATANODELIST']._serialized_start=370
  _globals['_DATANODELIST']._serialized_end=425
  _globals['_EMPTY']._serialized_start=427
  _globals['_EMPTY']._serialized_end=434
  _globals['_FILE']._serialized_start=437
  _globals['_FILE']._serialized_end=626
  _globals['_NAMENODESERVICE']._serialized_start=629
  _globals['_NAMENODESERVICE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
