# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import file_pb2 as file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_unary(
                '/File/download',
                request_serializer=file__pb2.FileDownloadReq.SerializeToString,
                response_deserializer=file__pb2.FileDownloadRsp.FromString,
                )
        self.listAll = channel.unary_stream(
                '/File/listAll',
                request_serializer=file__pb2.ListReq.SerializeToString,
                response_deserializer=file__pb2.FileListRsp.FromString,
                )
        self.listChunksFromFile = channel.unary_stream(
                '/File/listChunksFromFile',
                request_serializer=file__pb2.FileListReq.SerializeToString,
                response_deserializer=file__pb2.FileListRsp.FromString,
                )
        self.upload = channel.unary_unary(
                '/File/upload',
                request_serializer=file__pb2.FileUploadReq.SerializeToString,
                response_deserializer=file__pb2.UploadRsp.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listChunksFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=file__pb2.FileDownloadReq.FromString,
                    response_serializer=file__pb2.FileDownloadRsp.SerializeToString,
            ),
            'listAll': grpc.unary_stream_rpc_method_handler(
                    servicer.listAll,
                    request_deserializer=file__pb2.ListReq.FromString,
                    response_serializer=file__pb2.FileListRsp.SerializeToString,
            ),
            'listChunksFromFile': grpc.unary_stream_rpc_method_handler(
                    servicer.listChunksFromFile,
                    request_deserializer=file__pb2.FileListReq.FromString,
                    response_serializer=file__pb2.FileListRsp.SerializeToString,
            ),
            'upload': grpc.unary_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=file__pb2.FileUploadReq.FromString,
                    response_serializer=file__pb2.UploadRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/File/download',
            file__pb2.FileDownloadReq.SerializeToString,
            file__pb2.FileDownloadRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/listAll',
            file__pb2.ListReq.SerializeToString,
            file__pb2.FileListRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listChunksFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/listChunksFromFile',
            file__pb2.FileListReq.SerializeToString,
            file__pb2.FileListRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/File/upload',
            file__pb2.FileUploadReq.SerializeToString,
            file__pb2.UploadRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NameNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.open = channel.unary_stream(
                '/NameNodeService/open',
                request_serializer=file__pb2.FileOpenReq.SerializeToString,
                response_deserializer=file__pb2.DatanodeList.FromString,
                )
        self.create = channel.unary_stream(
                '/NameNodeService/create',
                request_serializer=file__pb2.FileCreateReq.SerializeToString,
                response_deserializer=file__pb2.DatanodeList.FromString,
                )
        self.ping = channel.unary_unary(
                '/NameNodeService/ping',
                request_serializer=file__pb2.Empty.SerializeToString,
                response_deserializer=file__pb2.Empty.FromString,
                )


class NameNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'open': grpc.unary_stream_rpc_method_handler(
                    servicer.open,
                    request_deserializer=file__pb2.FileOpenReq.FromString,
                    response_serializer=file__pb2.DatanodeList.SerializeToString,
            ),
            'create': grpc.unary_stream_rpc_method_handler(
                    servicer.create,
                    request_deserializer=file__pb2.FileCreateReq.FromString,
                    response_serializer=file__pb2.DatanodeList.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=file__pb2.Empty.FromString,
                    response_serializer=file__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NameNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NameNodeService/open',
            file__pb2.FileOpenReq.SerializeToString,
            file__pb2.DatanodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NameNodeService/create',
            file__pb2.FileCreateReq.SerializeToString,
            file__pb2.DatanodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameNodeService/ping',
            file__pb2.Empty.SerializeToString,
            file__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
