# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from . import namenode_pb2 as namenode__pb2


class NameNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.open = channel.unary_stream(
                '/NameNodeService/open',
                request_serializer=namenode__pb2.FileOpenReq.SerializeToString,
                response_deserializer=namenode__pb2.DatanodeList.FromString,
                )
        self.create = channel.unary_stream(
                '/NameNodeService/create',
                request_serializer=namenode__pb2.FileCreateReq.SerializeToString,
                response_deserializer=namenode__pb2.DatanodeList.FromString,
                )
        self.ping = channel.unary_unary(
                '/NameNodeService/ping',
                request_serializer=namenode__pb2.DatanodeInfo.SerializeToString,
                response_deserializer=namenode__pb2.Empty.FromString,
                )


class NameNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'open': grpc.unary_stream_rpc_method_handler(
                    servicer.open,
                    request_deserializer=namenode__pb2.FileOpenReq.FromString,
                    response_serializer=namenode__pb2.DatanodeList.SerializeToString,
            ),
            'create': grpc.unary_stream_rpc_method_handler(
                    servicer.create,
                    request_deserializer=namenode__pb2.FileCreateReq.FromString,
                    response_serializer=namenode__pb2.DatanodeList.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=namenode__pb2.DatanodeInfo.FromString,
                    response_serializer=namenode__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NameNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NameNodeService/open',
            namenode__pb2.FileOpenReq.SerializeToString,
            namenode__pb2.DatanodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NameNodeService/create',
            namenode__pb2.FileCreateReq.SerializeToString,
            namenode__pb2.DatanodeList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameNodeService/ping',
            namenode__pb2.DatanodeInfo.SerializeToString,
            namenode__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
