# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namenode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enamenode.proto\"\x1f\n\x0b\x46ileOpenReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"8\n\rFileCreateReq\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rchunks_number\x18\x02 \x01(\x03\"$\n\x0c\x44\x61tanodeList\x12\x14\n\x0clocalization\x18\x01 \x01(\t\"\x1e\n\x0c\x44\x61tanodeInfo\x12\x0e\n\x06socket\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x88\x01\n\x0fNameNodeService\x12\'\n\x04open\x12\x0c.FileOpenReq\x1a\r.DatanodeList\"\x00\x30\x01\x12+\n\x06\x63reate\x12\x0e.FileCreateReq\x1a\r.DatanodeList\"\x00\x30\x01\x12\x1f\n\x04ping\x12\r.DatanodeInfo\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namenode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEOPENREQ']._serialized_start=18
  _globals['_FILEOPENREQ']._serialized_end=49
  _globals['_FILECREATEREQ']._serialized_start=51
  _globals['_FILECREATEREQ']._serialized_end=107
  _globals['_DATANODELIST']._serialized_start=109
  _globals['_DATANODELIST']._serialized_end=145
  _globals['_DATANODEINFO']._serialized_start=147
  _globals['_DATANODEINFO']._serialized_end=177
  _globals['_EMPTY']._serialized_start=179
  _globals['_EMPTY']._serialized_end=186
  _globals['_NAMENODESERVICE']._serialized_start=189
  _globals['_NAMENODESERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
